// Code generated by MockGen. DO NOT EDIT.
// Source: artists.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockartistHandler is a mock of artistHandler interface.
type MockartistHandler struct {
	ctrl     *gomock.Controller
	recorder *MockartistHandlerMockRecorder
}

// MockartistHandlerMockRecorder is the mock recorder for MockartistHandler.
type MockartistHandlerMockRecorder struct {
	mock *MockartistHandler
}

// NewMockartistHandler creates a new mock instance.
func NewMockartistHandler(ctrl *gomock.Controller) *MockartistHandler {
	mock := &MockartistHandler{ctrl: ctrl}
	mock.recorder = &MockartistHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockartistHandler) EXPECT() *MockartistHandlerMockRecorder {
	return m.recorder
}

// ArtistByID mocks base method.
func (m *MockartistHandler) ArtistByID(c *gin.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArtistByID", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArtistByID indicates an expected call of ArtistByID.
func (mr *MockartistHandlerMockRecorder) ArtistByID(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArtistByID", reflect.TypeOf((*MockartistHandler)(nil).ArtistByID), c)
}

// CreateArtist mocks base method.
func (m *MockartistHandler) CreateArtist(c *gin.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArtist", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateArtist indicates an expected call of CreateArtist.
func (mr *MockartistHandlerMockRecorder) CreateArtist(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArtist", reflect.TypeOf((*MockartistHandler)(nil).CreateArtist), c)
}
