// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: playlist.proto

package playlist

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_playlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{0}
}

func (x *Playlist) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Playlist) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Playlist) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type PlaylistTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    int64                  `protobuf:"varint,1,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
	TrackId       int64                  `protobuf:"varint,2,opt,name=trackId,proto3" json:"trackId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistTrack) Reset() {
	*x = PlaylistTrack{}
	mi := &file_playlist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistTrack) ProtoMessage() {}

func (x *PlaylistTrack) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistTrack.ProtoReflect.Descriptor instead.
func (*PlaylistTrack) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{1}
}

func (x *PlaylistTrack) GetPlaylistId() int64 {
	if x != nil {
		return x.PlaylistId
	}
	return 0
}

func (x *PlaylistTrack) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

type CreatePlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylistRequest) Reset() {
	*x = CreatePlaylistRequest{}
	mi := &file_playlist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistRequest) ProtoMessage() {}

func (x *CreatePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlaylistRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePlaylistRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreatePlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaylistResponse) Reset() {
	*x = CreatePlaylistResponse{}
	mi := &file_playlist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaylistResponse) ProtoMessage() {}

func (x *CreatePlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaylistResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaylistResponse) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePlaylistResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistRequest) Reset() {
	*x = GetPlaylistRequest{}
	mi := &file_playlist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistRequest) ProtoMessage() {}

func (x *GetPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlaylistRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistResponse) Reset() {
	*x = GetPlaylistResponse{}
	mi := &file_playlist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistResponse) ProtoMessage() {}

func (x *GetPlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistResponse) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlaylistResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

type UpdatePlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlaylistRequest) Reset() {
	*x = UpdatePlaylistRequest{}
	mi := &file_playlist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylistRequest) ProtoMessage() {}

func (x *UpdatePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylistRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePlaylistRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePlaylistRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdatePlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlaylistResponse) Reset() {
	*x = UpdatePlaylistResponse{}
	mi := &file_playlist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylistResponse) ProtoMessage() {}

func (x *UpdatePlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylistResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlaylistResponse) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePlaylistResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

type DeletePlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlaylistRequest) Reset() {
	*x = DeletePlaylistRequest{}
	mi := &file_playlist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaylistRequest) ProtoMessage() {}

func (x *DeletePlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaylistRequest.ProtoReflect.Descriptor instead.
func (*DeletePlaylistRequest) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePlaylistRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlaylistResponse) Reset() {
	*x = DeletePlaylistResponse{}
	mi := &file_playlist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlaylistResponse) ProtoMessage() {}

func (x *DeletePlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlaylistResponse.ProtoReflect.Descriptor instead.
func (*DeletePlaylistResponse) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePlaylistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrackId       int64                  `protobuf:"varint,2,opt,name=trackId,proto3" json:"trackId,omitempty"`
	Position      int64                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackRequest) Reset() {
	*x = AddTrackRequest{}
	mi := &file_playlist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackRequest) ProtoMessage() {}

func (x *AddTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackRequest.ProtoReflect.Descriptor instead.
func (*AddTrackRequest) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{10}
}

func (x *AddTrackRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddTrackRequest) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *AddTrackRequest) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type RemoveTrackToPlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrackId       int64                  `protobuf:"varint,2,opt,name=trackId,proto3" json:"trackId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrackToPlaylistRequest) Reset() {
	*x = RemoveTrackToPlaylistRequest{}
	mi := &file_playlist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrackToPlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrackToPlaylistRequest) ProtoMessage() {}

func (x *RemoveTrackToPlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrackToPlaylistRequest.ProtoReflect.Descriptor instead.
func (*RemoveTrackToPlaylistRequest) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveTrackToPlaylistRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RemoveTrackToPlaylistRequest) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

type AddTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackResponse) Reset() {
	*x = AddTrackResponse{}
	mi := &file_playlist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackResponse) ProtoMessage() {}

func (x *AddTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackResponse.ProtoReflect.Descriptor instead.
func (*AddTrackResponse) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{12}
}

func (x *AddTrackResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveTrackToPlaylistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrackToPlaylistResponse) Reset() {
	*x = RemoveTrackToPlaylistResponse{}
	mi := &file_playlist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrackToPlaylistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrackToPlaylistResponse) ProtoMessage() {}

func (x *RemoveTrackToPlaylistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrackToPlaylistResponse.ProtoReflect.Descriptor instead.
func (*RemoveTrackToPlaylistResponse) Descriptor() ([]byte, []int) {
	return file_playlist_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveTrackToPlaylistResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_playlist_proto protoreflect.FileDescriptor

const file_playlist_proto_rawDesc = "" +
	"\n" +
	"\x0eplaylist.proto\x12\bplaylist\x1a\x1cgoogle/api/annotations.proto\"H\n" +
	"\bPlaylist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"I\n" +
	"\rPlaylistTrack\x12\x1e\n" +
	"\n" +
	"playlistId\x18\x01 \x01(\x03R\n" +
	"playlistId\x12\x18\n" +
	"\atrackId\x18\x02 \x01(\x03R\atrackId\"E\n" +
	"\x15CreatePlaylistRequest\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"(\n" +
	"\x16CreatePlaylistResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12GetPlaylistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x13GetPlaylistResponse\x12.\n" +
	"\bplaylist\x18\x01 \x01(\v2\x12.playlist.PlaylistR\bplaylist\"=\n" +
	"\x15UpdatePlaylistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"H\n" +
	"\x16UpdatePlaylistResponse\x12.\n" +
	"\bplaylist\x18\x01 \x01(\v2\x12.playlist.PlaylistR\bplaylist\"'\n" +
	"\x15DeletePlaylistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x16DeletePlaylistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x0fAddTrackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\atrackId\x18\x02 \x01(\x03R\atrackId\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\"H\n" +
	"\x1cRemoveTrackToPlaylistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\atrackId\x18\x02 \x01(\x03R\atrackId\"\"\n" +
	"\x10AddTrackResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x1dRemoveTrackToPlaylistResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xc0\x05\n" +
	"\x0fPlaylistService\x12b\n" +
	"\x06Create\x12\x1f.playlist.CreatePlaylistRequest\x1a .playlist.CreatePlaylistResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/playlists\x12c\n" +
	"\vGetPlaylist\x12\x1c.playlist.GetPlaylistRequest\x1a\x1d.playlist.GetPlaylistResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/playlists/{id}\x12o\n" +
	"\x0eUpdatePlaylist\x12\x1f.playlist.UpdatePlaylistRequest\x1a .playlist.UpdatePlaylistResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/playlists/{id}\x12l\n" +
	"\x0eDeletePlaylist\x12\x1f.playlist.DeletePlaylistRequest\x1a .playlist.DeletePlaylistResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/playlists/{id}\x12n\n" +
	"\x12AddTrackToPlaylist\x12\x19.playlist.AddTrackRequest\x1a\x1a.playlist.AddTrackResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/playlists/{id}/tracks\x12\x94\x01\n" +
	"\x17RemoveTrackFromPlaylist\x12&.playlist.RemoveTrackToPlaylistRequest\x1a'.playlist.RemoveTrackToPlaylistResponse\"(\x82\xd3\xe4\x93\x02\"* /playlists/{id}/tracks/{trackId}B\vZ\t/playlistb\x06proto3"

var (
	file_playlist_proto_rawDescOnce sync.Once
	file_playlist_proto_rawDescData []byte
)

func file_playlist_proto_rawDescGZIP() []byte {
	file_playlist_proto_rawDescOnce.Do(func() {
		file_playlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playlist_proto_rawDesc), len(file_playlist_proto_rawDesc)))
	})
	return file_playlist_proto_rawDescData
}

var file_playlist_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_playlist_proto_goTypes = []any{
	(*Playlist)(nil),                      // 0: playlist.Playlist
	(*PlaylistTrack)(nil),                 // 1: playlist.PlaylistTrack
	(*CreatePlaylistRequest)(nil),         // 2: playlist.CreatePlaylistRequest
	(*CreatePlaylistResponse)(nil),        // 3: playlist.CreatePlaylistResponse
	(*GetPlaylistRequest)(nil),            // 4: playlist.GetPlaylistRequest
	(*GetPlaylistResponse)(nil),           // 5: playlist.GetPlaylistResponse
	(*UpdatePlaylistRequest)(nil),         // 6: playlist.UpdatePlaylistRequest
	(*UpdatePlaylistResponse)(nil),        // 7: playlist.UpdatePlaylistResponse
	(*DeletePlaylistRequest)(nil),         // 8: playlist.DeletePlaylistRequest
	(*DeletePlaylistResponse)(nil),        // 9: playlist.DeletePlaylistResponse
	(*AddTrackRequest)(nil),               // 10: playlist.AddTrackRequest
	(*RemoveTrackToPlaylistRequest)(nil),  // 11: playlist.RemoveTrackToPlaylistRequest
	(*AddTrackResponse)(nil),              // 12: playlist.AddTrackResponse
	(*RemoveTrackToPlaylistResponse)(nil), // 13: playlist.RemoveTrackToPlaylistResponse
}
var file_playlist_proto_depIdxs = []int32{
	0,  // 0: playlist.GetPlaylistResponse.playlist:type_name -> playlist.Playlist
	0,  // 1: playlist.UpdatePlaylistResponse.playlist:type_name -> playlist.Playlist
	2,  // 2: playlist.PlaylistService.Create:input_type -> playlist.CreatePlaylistRequest
	4,  // 3: playlist.PlaylistService.GetPlaylist:input_type -> playlist.GetPlaylistRequest
	6,  // 4: playlist.PlaylistService.UpdatePlaylist:input_type -> playlist.UpdatePlaylistRequest
	8,  // 5: playlist.PlaylistService.DeletePlaylist:input_type -> playlist.DeletePlaylistRequest
	10, // 6: playlist.PlaylistService.AddTrackToPlaylist:input_type -> playlist.AddTrackRequest
	11, // 7: playlist.PlaylistService.RemoveTrackFromPlaylist:input_type -> playlist.RemoveTrackToPlaylistRequest
	3,  // 8: playlist.PlaylistService.Create:output_type -> playlist.CreatePlaylistResponse
	5,  // 9: playlist.PlaylistService.GetPlaylist:output_type -> playlist.GetPlaylistResponse
	7,  // 10: playlist.PlaylistService.UpdatePlaylist:output_type -> playlist.UpdatePlaylistResponse
	9,  // 11: playlist.PlaylistService.DeletePlaylist:output_type -> playlist.DeletePlaylistResponse
	12, // 12: playlist.PlaylistService.AddTrackToPlaylist:output_type -> playlist.AddTrackResponse
	13, // 13: playlist.PlaylistService.RemoveTrackFromPlaylist:output_type -> playlist.RemoveTrackToPlaylistResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_playlist_proto_init() }
func file_playlist_proto_init() {
	if File_playlist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playlist_proto_rawDesc), len(file_playlist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_playlist_proto_goTypes,
		DependencyIndexes: file_playlist_proto_depIdxs,
		MessageInfos:      file_playlist_proto_msgTypes,
	}.Build()
	File_playlist_proto = out.File
	file_playlist_proto_goTypes = nil
	file_playlist_proto_depIdxs = nil
}
