// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: request/request.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Album requests
type GetAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsRequest) Reset() {
	*x = GetAlbumsRequest{}
	mi := &file_request_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsRequest) ProtoMessage() {}

func (x *GetAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_request_request_proto_rawDescGZIP(), []int{0}
}

func (x *GetAlbumsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AlbumId       int64                  `protobuf:"varint,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAlbumRequest) Reset() {
	*x = AddAlbumRequest{}
	mi := &file_request_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAlbumRequest) ProtoMessage() {}

func (x *AddAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAlbumRequest.ProtoReflect.Descriptor instead.
func (*AddAlbumRequest) Descriptor() ([]byte, []int) {
	return file_request_request_proto_rawDescGZIP(), []int{1}
}

func (x *AddAlbumRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddAlbumRequest) GetAlbumId() int64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type DeleteAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AlbumId       int64                  `protobuf:"varint,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlbumRequest) Reset() {
	*x = DeleteAlbumRequest{}
	mi := &file_request_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumRequest) ProtoMessage() {}

func (x *DeleteAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlbumRequest) Descriptor() ([]byte, []int) {
	return file_request_request_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAlbumRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteAlbumRequest) GetAlbumId() int64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

// Artist requests
type AddArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArtistId      int64                  `protobuf:"varint,2,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArtistRequest) Reset() {
	*x = AddArtistRequest{}
	mi := &file_request_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArtistRequest) ProtoMessage() {}

func (x *AddArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArtistRequest.ProtoReflect.Descriptor instead.
func (*AddArtistRequest) Descriptor() ([]byte, []int) {
	return file_request_request_proto_rawDescGZIP(), []int{3}
}

func (x *AddArtistRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddArtistRequest) GetArtistId() int64 {
	if x != nil {
		return x.ArtistId
	}
	return 0
}

type GetArtistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistsRequest) Reset() {
	*x = GetArtistsRequest{}
	mi := &file_request_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistsRequest) ProtoMessage() {}

func (x *GetArtistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistsRequest.ProtoReflect.Descriptor instead.
func (*GetArtistsRequest) Descriptor() ([]byte, []int) {
	return file_request_request_proto_rawDescGZIP(), []int{4}
}

func (x *GetArtistsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArtistId      int64                  `protobuf:"varint,2,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtistRequest) Reset() {
	*x = DeleteArtistRequest{}
	mi := &file_request_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtistRequest) ProtoMessage() {}

func (x *DeleteArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtistRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtistRequest) Descriptor() ([]byte, []int) {
	return file_request_request_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteArtistRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteArtistRequest) GetArtistId() int64 {
	if x != nil {
		return x.ArtistId
	}
	return 0
}

// Track requests
type AddTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrackId       int64                  `protobuf:"varint,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackRequest) Reset() {
	*x = AddTrackRequest{}
	mi := &file_request_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackRequest) ProtoMessage() {}

func (x *AddTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackRequest.ProtoReflect.Descriptor instead.
func (*AddTrackRequest) Descriptor() ([]byte, []int) {
	return file_request_request_proto_rawDescGZIP(), []int{6}
}

func (x *AddTrackRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddTrackRequest) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

type GetTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracksRequest) Reset() {
	*x = GetTracksRequest{}
	mi := &file_request_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracksRequest) ProtoMessage() {}

func (x *GetTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracksRequest.ProtoReflect.Descriptor instead.
func (*GetTracksRequest) Descriptor() ([]byte, []int) {
	return file_request_request_proto_rawDescGZIP(), []int{7}
}

func (x *GetTracksRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrackId       int64                  `protobuf:"varint,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTrackRequest) Reset() {
	*x = DeleteTrackRequest{}
	mi := &file_request_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrackRequest) ProtoMessage() {}

func (x *DeleteTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrackRequest.ProtoReflect.Descriptor instead.
func (*DeleteTrackRequest) Descriptor() ([]byte, []int) {
	return file_request_request_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTrackRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteTrackRequest) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

var File_request_request_proto protoreflect.FileDescriptor

const file_request_request_proto_rawDesc = "" +
	"\n" +
	"\x15request/request.proto\x12\arequest\"+\n" +
	"\x10GetAlbumsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"E\n" +
	"\x0fAddAlbumRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\balbum_id\x18\x02 \x01(\x03R\aalbumId\"H\n" +
	"\x12DeleteAlbumRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\balbum_id\x18\x02 \x01(\x03R\aalbumId\"H\n" +
	"\x10AddArtistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tartist_id\x18\x02 \x01(\x03R\bartistId\",\n" +
	"\x11GetArtistsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"K\n" +
	"\x13DeleteArtistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tartist_id\x18\x02 \x01(\x03R\bartistId\"E\n" +
	"\x0fAddTrackRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\x03R\atrackId\"+\n" +
	"\x10GetTracksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"H\n" +
	"\x12DeleteTrackRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\x03R\atrackIdB*Z(collection-service/proto/request;requestb\x06proto3"

var (
	file_request_request_proto_rawDescOnce sync.Once
	file_request_request_proto_rawDescData []byte
)

func file_request_request_proto_rawDescGZIP() []byte {
	file_request_request_proto_rawDescOnce.Do(func() {
		file_request_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_request_proto_rawDesc), len(file_request_request_proto_rawDesc)))
	})
	return file_request_request_proto_rawDescData
}

var file_request_request_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_request_request_proto_goTypes = []any{
	(*GetAlbumsRequest)(nil),    // 0: request.GetAlbumsRequest
	(*AddAlbumRequest)(nil),     // 1: request.AddAlbumRequest
	(*DeleteAlbumRequest)(nil),  // 2: request.DeleteAlbumRequest
	(*AddArtistRequest)(nil),    // 3: request.AddArtistRequest
	(*GetArtistsRequest)(nil),   // 4: request.GetArtistsRequest
	(*DeleteArtistRequest)(nil), // 5: request.DeleteArtistRequest
	(*AddTrackRequest)(nil),     // 6: request.AddTrackRequest
	(*GetTracksRequest)(nil),    // 7: request.GetTracksRequest
	(*DeleteTrackRequest)(nil),  // 8: request.DeleteTrackRequest
}
var file_request_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_request_proto_init() }
func file_request_request_proto_init() {
	if File_request_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_request_proto_rawDesc), len(file_request_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_request_proto_goTypes,
		DependencyIndexes: file_request_request_proto_depIdxs,
		MessageInfos:      file_request_request_proto_msgTypes,
	}.Build()
	File_request_request_proto = out.File
	file_request_request_proto_goTypes = nil
	file_request_request_proto_depIdxs = nil
}
