// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: collection/collection.proto

package collection

import (
	"music/collection-service/proto/request"
	"music/collection-service/proto/response"
	reflect "reflect"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_collection_collection_proto protoreflect.FileDescriptor

const file_collection_collection_proto_rawDesc = "" +
	"\n" +
	"\x1bcollection/collection.proto\x12\n" +
	"collection\x1a\x15request/request.proto\x1a\x17response/response.proto\x1a\x1cgoogle/api/annotations.proto2\x93\b\n" +
	"\x11CollectionService\x12j\n" +
	"\x14AddAlbumToCollection\x12\x18.request.AddAlbumRequest\x1a\x1a.response.AddAlbumResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/album_collection\x12h\n" +
	"\x13GetAlbumsCollection\x12\x19.request.GetAlbumsRequest\x1a\x1b.response.GetAlbumsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/album_collection\x12y\n" +
	"\x15DeleteAlbumCollection\x12\x1b.request.DeleteAlbumRequest\x1a\x1d.response.DeleteAlbumResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/album_collection/{album_id}\x12n\n" +
	"\x15AddArtistToCollection\x12\x19.request.AddArtistRequest\x1a\x1b.response.AddArtistResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/artist_collection\x12l\n" +
	"\x14GetArtistsCollection\x12\x1a.request.GetArtistsRequest\x1a\x1c.response.GetArtistsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/artist_collection\x12~\n" +
	"\x16DeleteArtistCollection\x12\x1c.request.DeleteArtistRequest\x1a\x1e.response.DeleteArtistResponse\"&\x82\xd3\xe4\x93\x02 *\x1e/artist_collection/{artist_id}\x12j\n" +
	"\x14AddTrackToCollection\x12\x18.request.AddTrackRequest\x1a\x1a.response.AddTrackResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/track_collection\x12h\n" +
	"\x13GetTracksCollection\x12\x19.request.GetTracksRequest\x1a\x1b.response.GetTracksResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/track_collection\x12y\n" +
	"\x15DeleteTrackCollection\x12\x1b.request.DeleteTrackRequest\x1a\x1d.response.DeleteTrackResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/track_collection/{track_id}B0Z.collection-service/proto/collection;collectionb\x06proto3"

var file_collection_collection_proto_goTypes = []any{
	(*request.AddAlbumRequest)(nil),       // 0: request.AddAlbumRequest
	(*request.GetAlbumsRequest)(nil),      // 1: request.GetAlbumsRequest
	(*request.DeleteAlbumRequest)(nil),    // 2: request.DeleteAlbumRequest
	(*request.AddArtistRequest)(nil),      // 3: request.AddArtistRequest
	(*request.GetArtistsRequest)(nil),     // 4: request.GetArtistsRequest
	(*request.DeleteArtistRequest)(nil),   // 5: request.DeleteArtistRequest
	(*request.AddTrackRequest)(nil),       // 6: request.AddTrackRequest
	(*request.GetTracksRequest)(nil),      // 7: request.GetTracksRequest
	(*request.DeleteTrackRequest)(nil),    // 8: request.DeleteTrackRequest
	(*response.AddAlbumResponse)(nil),     // 9: response.AddAlbumResponse
	(*response.GetAlbumsResponse)(nil),    // 10: response.GetAlbumsResponse
	(*response.DeleteAlbumResponse)(nil),  // 11: response.DeleteAlbumResponse
	(*response.AddArtistResponse)(nil),    // 12: response.AddArtistResponse
	(*response.GetArtistsResponse)(nil),   // 13: response.GetArtistsResponse
	(*response.DeleteArtistResponse)(nil), // 14: response.DeleteArtistResponse
	(*response.AddTrackResponse)(nil),     // 15: response.AddTrackResponse
	(*response.GetTracksResponse)(nil),    // 16: response.GetTracksResponse
	(*response.DeleteTrackResponse)(nil),  // 17: response.DeleteTrackResponse
}
var file_collection_collection_proto_depIdxs = []int32{
	0,  // 0: collection.CollectionService.AddAlbumToCollection:input_type -> request.AddAlbumRequest
	1,  // 1: collection.CollectionService.GetAlbumsCollection:input_type -> request.GetAlbumsRequest
	2,  // 2: collection.CollectionService.DeleteAlbumCollection:input_type -> request.DeleteAlbumRequest
	3,  // 3: collection.CollectionService.AddArtistToCollection:input_type -> request.AddArtistRequest
	4,  // 4: collection.CollectionService.GetArtistsCollection:input_type -> request.GetArtistsRequest
	5,  // 5: collection.CollectionService.DeleteArtistCollection:input_type -> request.DeleteArtistRequest
	6,  // 6: collection.CollectionService.AddTrackToCollection:input_type -> request.AddTrackRequest
	7,  // 7: collection.CollectionService.GetTracksCollection:input_type -> request.GetTracksRequest
	8,  // 8: collection.CollectionService.DeleteTrackCollection:input_type -> request.DeleteTrackRequest
	9,  // 9: collection.CollectionService.AddAlbumToCollection:output_type -> response.AddAlbumResponse
	10, // 10: collection.CollectionService.GetAlbumsCollection:output_type -> response.GetAlbumsResponse
	11, // 11: collection.CollectionService.DeleteAlbumCollection:output_type -> response.DeleteAlbumResponse
	12, // 12: collection.CollectionService.AddArtistToCollection:output_type -> response.AddArtistResponse
	13, // 13: collection.CollectionService.GetArtistsCollection:output_type -> response.GetArtistsResponse
	14, // 14: collection.CollectionService.DeleteArtistCollection:output_type -> response.DeleteArtistResponse
	15, // 15: collection.CollectionService.AddTrackToCollection:output_type -> response.AddTrackResponse
	16, // 16: collection.CollectionService.GetTracksCollection:output_type -> response.GetTracksResponse
	17, // 17: collection.CollectionService.DeleteTrackCollection:output_type -> response.DeleteTrackResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_collection_collection_proto_init() }
func file_collection_collection_proto_init() {
	if File_collection_collection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collection_collection_proto_rawDesc), len(file_collection_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collection_collection_proto_goTypes,
		DependencyIndexes: file_collection_collection_proto_depIdxs,
	}.Build()
	File_collection_collection_proto = out.File
	file_collection_collection_proto_goTypes = nil
	file_collection_collection_proto_depIdxs = nil
}
