// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: collection/collection.proto

package collection

import (
	context "context"
	"music/collection-service/proto/request"
	"music/collection-service/proto/response"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollectionService_AddAlbumToCollection_FullMethodName   = "/collection.CollectionService/AddAlbumToCollection"
	CollectionService_GetAlbumsCollection_FullMethodName    = "/collection.CollectionService/GetAlbumsCollection"
	CollectionService_DeleteAlbumCollection_FullMethodName  = "/collection.CollectionService/DeleteAlbumCollection"
	CollectionService_AddArtistToCollection_FullMethodName  = "/collection.CollectionService/AddArtistToCollection"
	CollectionService_GetArtistsCollection_FullMethodName   = "/collection.CollectionService/GetArtistsCollection"
	CollectionService_DeleteArtistCollection_FullMethodName = "/collection.CollectionService/DeleteArtistCollection"
	CollectionService_AddTrackToCollection_FullMethodName   = "/collection.CollectionService/AddTrackToCollection"
	CollectionService_GetTracksCollection_FullMethodName    = "/collection.CollectionService/GetTracksCollection"
	CollectionService_DeleteTrackCollection_FullMethodName  = "/collection.CollectionService/DeleteTrackCollection"
)

// CollectionServiceClient is the client API for CollectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectionServiceClient interface {
	// Альбомы
	AddAlbumToCollection(ctx context.Context, in *request.AddAlbumRequest, opts ...grpc.CallOption) (*response.AddAlbumResponse, error)
	GetAlbumsCollection(ctx context.Context, in *request.GetAlbumsRequest, opts ...grpc.CallOption) (*response.GetAlbumsResponse, error)
	DeleteAlbumCollection(ctx context.Context, in *request.DeleteAlbumRequest, opts ...grpc.CallOption) (*response.DeleteAlbumResponse, error)
	// Артисты
	AddArtistToCollection(ctx context.Context, in *request.AddArtistRequest, opts ...grpc.CallOption) (*response.AddArtistResponse, error)
	GetArtistsCollection(ctx context.Context, in *request.GetArtistsRequest, opts ...grpc.CallOption) (*response.GetArtistsResponse, error)
	DeleteArtistCollection(ctx context.Context, in *request.DeleteArtistRequest, opts ...grpc.CallOption) (*response.DeleteArtistResponse, error)
	// Треки
	AddTrackToCollection(ctx context.Context, in *request.AddTrackRequest, opts ...grpc.CallOption) (*response.AddTrackResponse, error)
	GetTracksCollection(ctx context.Context, in *request.GetTracksRequest, opts ...grpc.CallOption) (*response.GetTracksResponse, error)
	DeleteTrackCollection(ctx context.Context, in *request.DeleteTrackRequest, opts ...grpc.CallOption) (*response.DeleteTrackResponse, error)
}

type collectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectionServiceClient(cc grpc.ClientConnInterface) CollectionServiceClient {
	return &collectionServiceClient{cc}
}

func (c *collectionServiceClient) AddAlbumToCollection(ctx context.Context, in *request.AddAlbumRequest, opts ...grpc.CallOption) (*response.AddAlbumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.AddAlbumResponse)
	err := c.cc.Invoke(ctx, CollectionService_AddAlbumToCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) GetAlbumsCollection(ctx context.Context, in *request.GetAlbumsRequest, opts ...grpc.CallOption) (*response.GetAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GetAlbumsResponse)
	err := c.cc.Invoke(ctx, CollectionService_GetAlbumsCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) DeleteAlbumCollection(ctx context.Context, in *request.DeleteAlbumRequest, opts ...grpc.CallOption) (*response.DeleteAlbumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.DeleteAlbumResponse)
	err := c.cc.Invoke(ctx, CollectionService_DeleteAlbumCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) AddArtistToCollection(ctx context.Context, in *request.AddArtistRequest, opts ...grpc.CallOption) (*response.AddArtistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.AddArtistResponse)
	err := c.cc.Invoke(ctx, CollectionService_AddArtistToCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) GetArtistsCollection(ctx context.Context, in *request.GetArtistsRequest, opts ...grpc.CallOption) (*response.GetArtistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GetArtistsResponse)
	err := c.cc.Invoke(ctx, CollectionService_GetArtistsCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) DeleteArtistCollection(ctx context.Context, in *request.DeleteArtistRequest, opts ...grpc.CallOption) (*response.DeleteArtistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.DeleteArtistResponse)
	err := c.cc.Invoke(ctx, CollectionService_DeleteArtistCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) AddTrackToCollection(ctx context.Context, in *request.AddTrackRequest, opts ...grpc.CallOption) (*response.AddTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.AddTrackResponse)
	err := c.cc.Invoke(ctx, CollectionService_AddTrackToCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) GetTracksCollection(ctx context.Context, in *request.GetTracksRequest, opts ...grpc.CallOption) (*response.GetTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GetTracksResponse)
	err := c.cc.Invoke(ctx, CollectionService_GetTracksCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) DeleteTrackCollection(ctx context.Context, in *request.DeleteTrackRequest, opts ...grpc.CallOption) (*response.DeleteTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.DeleteTrackResponse)
	err := c.cc.Invoke(ctx, CollectionService_DeleteTrackCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectionServiceServer is the server API for CollectionService service.
// All implementations must embed UnimplementedCollectionServiceServer
// for forward compatibility.
type CollectionServiceServer interface {
	// Альбомы
	AddAlbumToCollection(context.Context, *request.AddAlbumRequest) (*response.AddAlbumResponse, error)
	GetAlbumsCollection(context.Context, *request.GetAlbumsRequest) (*response.GetAlbumsResponse, error)
	DeleteAlbumCollection(context.Context, *request.DeleteAlbumRequest) (*response.DeleteAlbumResponse, error)
	// Артисты
	AddArtistToCollection(context.Context, *request.AddArtistRequest) (*response.AddArtistResponse, error)
	GetArtistsCollection(context.Context, *request.GetArtistsRequest) (*response.GetArtistsResponse, error)
	DeleteArtistCollection(context.Context, *request.DeleteArtistRequest) (*response.DeleteArtistResponse, error)
	// Треки
	AddTrackToCollection(context.Context, *request.AddTrackRequest) (*response.AddTrackResponse, error)
	GetTracksCollection(context.Context, *request.GetTracksRequest) (*response.GetTracksResponse, error)
	DeleteTrackCollection(context.Context, *request.DeleteTrackRequest) (*response.DeleteTrackResponse, error)
	mustEmbedUnimplementedCollectionServiceServer()
}

// UnimplementedCollectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectionServiceServer struct{}

func (UnimplementedCollectionServiceServer) AddAlbumToCollection(context.Context, *request.AddAlbumRequest) (*response.AddAlbumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAlbumToCollection not implemented")
}
func (UnimplementedCollectionServiceServer) GetAlbumsCollection(context.Context, *request.GetAlbumsRequest) (*response.GetAlbumsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlbumsCollection not implemented")
}
func (UnimplementedCollectionServiceServer) DeleteAlbumCollection(context.Context, *request.DeleteAlbumRequest) (*response.DeleteAlbumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAlbumCollection not implemented")
}
func (UnimplementedCollectionServiceServer) AddArtistToCollection(context.Context, *request.AddArtistRequest) (*response.AddArtistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddArtistToCollection not implemented")
}
func (UnimplementedCollectionServiceServer) GetArtistsCollection(context.Context, *request.GetArtistsRequest) (*response.GetArtistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtistsCollection not implemented")
}
func (UnimplementedCollectionServiceServer) DeleteArtistCollection(context.Context, *request.DeleteArtistRequest) (*response.DeleteArtistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArtistCollection not implemented")
}
func (UnimplementedCollectionServiceServer) AddTrackToCollection(context.Context, *request.AddTrackRequest) (*response.AddTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTrackToCollection not implemented")
}
func (UnimplementedCollectionServiceServer) GetTracksCollection(context.Context, *request.GetTracksRequest) (*response.GetTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTracksCollection not implemented")
}
func (UnimplementedCollectionServiceServer) DeleteTrackCollection(context.Context, *request.DeleteTrackRequest) (*response.DeleteTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTrackCollection not implemented")
}
func (UnimplementedCollectionServiceServer) mustEmbedUnimplementedCollectionServiceServer() {}
func (UnimplementedCollectionServiceServer) testEmbeddedByValue()                           {}

// UnsafeCollectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectionServiceServer will
// result in compilation errors.
type UnsafeCollectionServiceServer interface {
	mustEmbedUnimplementedCollectionServiceServer()
}

func RegisterCollectionServiceServer(s grpc.ServiceRegistrar, srv CollectionServiceServer) {
	// If the following call panics, it indicates UnimplementedCollectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectionService_ServiceDesc, srv)
}

func _CollectionService_AddAlbumToCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.AddAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).AddAlbumToCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionService_AddAlbumToCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).AddAlbumToCollection(ctx, req.(*request.AddAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_GetAlbumsCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).GetAlbumsCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionService_GetAlbumsCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).GetAlbumsCollection(ctx, req.(*request.GetAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_DeleteAlbumCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.DeleteAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).DeleteAlbumCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionService_DeleteAlbumCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).DeleteAlbumCollection(ctx, req.(*request.DeleteAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_AddArtistToCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.AddArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).AddArtistToCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionService_AddArtistToCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).AddArtistToCollection(ctx, req.(*request.AddArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_GetArtistsCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetArtistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).GetArtistsCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionService_GetArtistsCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).GetArtistsCollection(ctx, req.(*request.GetArtistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_DeleteArtistCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.DeleteArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).DeleteArtistCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionService_DeleteArtistCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).DeleteArtistCollection(ctx, req.(*request.DeleteArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_AddTrackToCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.AddTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).AddTrackToCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionService_AddTrackToCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).AddTrackToCollection(ctx, req.(*request.AddTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_GetTracksCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).GetTracksCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionService_GetTracksCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).GetTracksCollection(ctx, req.(*request.GetTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_DeleteTrackCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.DeleteTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).DeleteTrackCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionService_DeleteTrackCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).DeleteTrackCollection(ctx, req.(*request.DeleteTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectionService_ServiceDesc is the grpc.ServiceDesc for CollectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collection.CollectionService",
	HandlerType: (*CollectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAlbumToCollection",
			Handler:    _CollectionService_AddAlbumToCollection_Handler,
		},
		{
			MethodName: "GetAlbumsCollection",
			Handler:    _CollectionService_GetAlbumsCollection_Handler,
		},
		{
			MethodName: "DeleteAlbumCollection",
			Handler:    _CollectionService_DeleteAlbumCollection_Handler,
		},
		{
			MethodName: "AddArtistToCollection",
			Handler:    _CollectionService_AddArtistToCollection_Handler,
		},
		{
			MethodName: "GetArtistsCollection",
			Handler:    _CollectionService_GetArtistsCollection_Handler,
		},
		{
			MethodName: "DeleteArtistCollection",
			Handler:    _CollectionService_DeleteArtistCollection_Handler,
		},
		{
			MethodName: "AddTrackToCollection",
			Handler:    _CollectionService_AddTrackToCollection_Handler,
		},
		{
			MethodName: "GetTracksCollection",
			Handler:    _CollectionService_GetTracksCollection_Handler,
		},
		{
			MethodName: "DeleteTrackCollection",
			Handler:    _CollectionService_DeleteTrackCollection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collection/collection.proto",
}
