// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: response/response.proto

package response

import (
	"music/collection-service/proto/models"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Album requests
type GetAlbumsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albums        []*models.Album        `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsResponse) Reset() {
	*x = GetAlbumsResponse{}
	mi := &file_response_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsResponse) ProtoMessage() {}

func (x *GetAlbumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsResponse.ProtoReflect.Descriptor instead.
func (*GetAlbumsResponse) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{0}
}

func (x *GetAlbumsResponse) GetAlbums() []*models.Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

type AddAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       int64                  `protobuf:"varint,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAlbumResponse) Reset() {
	*x = AddAlbumResponse{}
	mi := &file_response_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAlbumResponse) ProtoMessage() {}

func (x *AddAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAlbumResponse.ProtoReflect.Descriptor instead.
func (*AddAlbumResponse) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{1}
}

func (x *AddAlbumResponse) GetAlbumId() int64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type DeleteAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       int64                  `protobuf:"varint,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlbumResponse) Reset() {
	*x = DeleteAlbumResponse{}
	mi := &file_response_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumResponse) ProtoMessage() {}

func (x *DeleteAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlbumResponse) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAlbumResponse) GetAlbumId() int64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

// Artist requests
type AddArtistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistId      int64                  `protobuf:"varint,2,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArtistResponse) Reset() {
	*x = AddArtistResponse{}
	mi := &file_response_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArtistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArtistResponse) ProtoMessage() {}

func (x *AddArtistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArtistResponse.ProtoReflect.Descriptor instead.
func (*AddArtistResponse) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{3}
}

func (x *AddArtistResponse) GetArtistId() int64 {
	if x != nil {
		return x.ArtistId
	}
	return 0
}

type GetArtistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artists       []*models.Artist       `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistsResponse) Reset() {
	*x = GetArtistsResponse{}
	mi := &file_response_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistsResponse) ProtoMessage() {}

func (x *GetArtistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistsResponse.ProtoReflect.Descriptor instead.
func (*GetArtistsResponse) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{4}
}

func (x *GetArtistsResponse) GetArtists() []*models.Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

type DeleteArtistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistId      int64                  `protobuf:"varint,2,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtistResponse) Reset() {
	*x = DeleteArtistResponse{}
	mi := &file_response_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtistResponse) ProtoMessage() {}

func (x *DeleteArtistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtistResponse.ProtoReflect.Descriptor instead.
func (*DeleteArtistResponse) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteArtistResponse) GetArtistId() int64 {
	if x != nil {
		return x.ArtistId
	}
	return 0
}

// Track requests
type AddTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       int64                  `protobuf:"varint,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackResponse) Reset() {
	*x = AddTrackResponse{}
	mi := &file_response_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackResponse) ProtoMessage() {}

func (x *AddTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackResponse.ProtoReflect.Descriptor instead.
func (*AddTrackResponse) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{6}
}

func (x *AddTrackResponse) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

type GetTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*models.Track        `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTracksResponse) Reset() {
	*x = GetTracksResponse{}
	mi := &file_response_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracksResponse) ProtoMessage() {}

func (x *GetTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracksResponse.ProtoReflect.Descriptor instead.
func (*GetTracksResponse) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{7}
}

func (x *GetTracksResponse) GetTracks() []*models.Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type DeleteTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       int64                  `protobuf:"varint,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTrackResponse) Reset() {
	*x = DeleteTrackResponse{}
	mi := &file_response_response_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrackResponse) ProtoMessage() {}

func (x *DeleteTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrackResponse.ProtoReflect.Descriptor instead.
func (*DeleteTrackResponse) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTrackResponse) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

var File_response_response_proto protoreflect.FileDescriptor

const file_response_response_proto_rawDesc = "" +
	"\n" +
	"\x17response/response.proto\x12\bresponse\x1a\x13models/models.proto\":\n" +
	"\x11GetAlbumsResponse\x12%\n" +
	"\x06albums\x18\x01 \x03(\v2\r.models.AlbumR\x06albums\"-\n" +
	"\x10AddAlbumResponse\x12\x19\n" +
	"\balbum_id\x18\x02 \x01(\x03R\aalbumId\"0\n" +
	"\x13DeleteAlbumResponse\x12\x19\n" +
	"\balbum_id\x18\x02 \x01(\x03R\aalbumId\"0\n" +
	"\x11AddArtistResponse\x12\x1b\n" +
	"\tartist_id\x18\x02 \x01(\x03R\bartistId\">\n" +
	"\x12GetArtistsResponse\x12(\n" +
	"\aartists\x18\x01 \x03(\v2\x0e.models.ArtistR\aartists\"3\n" +
	"\x14DeleteArtistResponse\x12\x1b\n" +
	"\tartist_id\x18\x02 \x01(\x03R\bartistId\"-\n" +
	"\x10AddTrackResponse\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\x03R\atrackId\":\n" +
	"\x11GetTracksResponse\x12%\n" +
	"\x06tracks\x18\x01 \x03(\v2\r.models.TrackR\x06tracks\"0\n" +
	"\x13DeleteTrackResponse\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\x03R\atrackIdB,Z*collection-service/proto/response;responseb\x06proto3"

var (
	file_response_response_proto_rawDescOnce sync.Once
	file_response_response_proto_rawDescData []byte
)

func file_response_response_proto_rawDescGZIP() []byte {
	file_response_response_proto_rawDescOnce.Do(func() {
		file_response_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_response_proto_rawDesc), len(file_response_response_proto_rawDesc)))
	})
	return file_response_response_proto_rawDescData
}

var file_response_response_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_response_response_proto_goTypes = []any{
	(*GetAlbumsResponse)(nil),    // 0: response.GetAlbumsResponse
	(*AddAlbumResponse)(nil),     // 1: response.AddAlbumResponse
	(*DeleteAlbumResponse)(nil),  // 2: response.DeleteAlbumResponse
	(*AddArtistResponse)(nil),    // 3: response.AddArtistResponse
	(*GetArtistsResponse)(nil),   // 4: response.GetArtistsResponse
	(*DeleteArtistResponse)(nil), // 5: response.DeleteArtistResponse
	(*AddTrackResponse)(nil),     // 6: response.AddTrackResponse
	(*GetTracksResponse)(nil),    // 7: response.GetTracksResponse
	(*DeleteTrackResponse)(nil),  // 8: response.DeleteTrackResponse
	(*models.Album)(nil),         // 9: models.Album
	(*models.Artist)(nil),        // 10: models.Artist
	(*models.Track)(nil),         // 11: models.Track
}
var file_response_response_proto_depIdxs = []int32{
	9,  // 0: response.GetAlbumsResponse.albums:type_name -> models.Album
	10, // 1: response.GetArtistsResponse.artists:type_name -> models.Artist
	11, // 2: response.GetTracksResponse.tracks:type_name -> models.Track
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_response_response_proto_init() }
func file_response_response_proto_init() {
	if File_response_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_response_proto_rawDesc), len(file_response_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_response_proto_goTypes,
		DependencyIndexes: file_response_response_proto_depIdxs,
		MessageInfos:      file_response_response_proto_msgTypes,
	}.Build()
	File_response_response_proto = out.File
	file_response_response_proto_goTypes = nil
	file_response_response_proto_depIdxs = nil
}
