env: "local"
grpc_port: 50051
http_port: 8080
db_host: "localhost"
db_port: "5432"
db_user: "postgres"
db_password: "postgres"
db_name: "catalog_service"
max_conns: 20
min_conns: 10
max_conn_idle: 30
conn_timeout: 30
redis_host: "localhost"
redis_port: "6379"
