// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: track.proto

package track

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Duration      int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	AudioURL      string                 `protobuf:"bytes,4,opt,name=audioURL,proto3" json:"audioURL,omitempty"`
	ArtistId      int64                  `protobuf:"varint,5,opt,name=artistId,proto3" json:"artistId,omitempty"`
	AlbumId       int64                  `protobuf:"varint,6,opt,name=albumId,proto3" json:"albumId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_track_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Track) GetAudioURL() string {
	if x != nil {
		return x.AudioURL
	}
	return ""
}

func (x *Track) GetArtistId() int64 {
	if x != nil {
		return x.ArtistId
	}
	return 0
}

func (x *Track) GetAlbumId() int64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type CreateTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *Track                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackRequest) Reset() {
	*x = CreateTrackRequest{}
	mi := &file_track_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackRequest) ProtoMessage() {}

func (x *CreateTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackRequest.ProtoReflect.Descriptor instead.
func (*CreateTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTrackRequest) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

type CreateTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackResponse) Reset() {
	*x = CreateTrackResponse{}
	mi := &file_track_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackResponse) ProtoMessage() {}

func (x *CreateTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackResponse.ProtoReflect.Descriptor instead.
func (*CreateTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTrackResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackRequest) Reset() {
	*x = GetTrackRequest{}
	mi := &file_track_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackRequest) ProtoMessage() {}

func (x *GetTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackRequest.ProtoReflect.Descriptor instead.
func (*GetTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrackRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *Track                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackResponse) Reset() {
	*x = GetTrackResponse{}
	mi := &file_track_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackResponse) ProtoMessage() {}

func (x *GetTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackResponse.ProtoReflect.Descriptor instead.
func (*GetTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{4}
}

func (x *GetTrackResponse) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

type UpdateTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Track         *Track                 `protobuf:"bytes,2,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrackRequest) Reset() {
	*x = UpdateTrackRequest{}
	mi := &file_track_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrackRequest) ProtoMessage() {}

func (x *UpdateTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrackRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTrackRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTrackRequest) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

type UpdateTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrackResponse) Reset() {
	*x = UpdateTrackResponse{}
	mi := &file_track_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrackResponse) ProtoMessage() {}

func (x *UpdateTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrackResponse.ProtoReflect.Descriptor instead.
func (*UpdateTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTrackResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTrackRequest) Reset() {
	*x = DeleteTrackRequest{}
	mi := &file_track_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrackRequest) ProtoMessage() {}

func (x *DeleteTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrackRequest.ProtoReflect.Descriptor instead.
func (*DeleteTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTrackRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTrackResponse) Reset() {
	*x = DeleteTrackResponse{}
	mi := &file_track_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrackResponse) ProtoMessage() {}

func (x *DeleteTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrackResponse.ProtoReflect.Descriptor instead.
func (*DeleteTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTrackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_track_proto protoreflect.FileDescriptor

const file_track_proto_rawDesc = "" +
	"\n" +
	"\vtrack.proto\x12\x05track\x1a\x1cgoogle/api/annotations.proto\"\x9b\x01\n" +
	"\x05Track\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x03R\bduration\x12\x1a\n" +
	"\baudioURL\x18\x04 \x01(\tR\baudioURL\x12\x1a\n" +
	"\bartistId\x18\x05 \x01(\x03R\bartistId\x12\x18\n" +
	"\aalbumId\x18\x06 \x01(\x03R\aalbumId\"8\n" +
	"\x12CreateTrackRequest\x12\"\n" +
	"\x05track\x18\x01 \x01(\v2\f.track.TrackR\x05track\"%\n" +
	"\x13CreateTrackResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"!\n" +
	"\x0fGetTrackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"6\n" +
	"\x10GetTrackResponse\x12\"\n" +
	"\x05track\x18\x01 \x01(\v2\f.track.TrackR\x05track\"H\n" +
	"\x12UpdateTrackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\x05track\x18\x02 \x01(\v2\f.track.TrackR\x05track\"%\n" +
	"\x13UpdateTrackResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12DeleteTrackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x13DeleteTrackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf5\x02\n" +
	"\vUserService\x12X\n" +
	"\vCreateTrack\x12\x19.track.CreateTrackRequest\x1a\x1a.track.CreateTrackResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/tracks\x12Q\n" +
	"\bGetTrack\x12\x16.track.GetTrackRequest\x1a\x17.track.GetTrackResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/tracks/{id}\x12]\n" +
	"\vUpdateTrack\x12\x19.track.UpdateTrackRequest\x1a\x1a.track.UpdateTrackResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*2\f/tracks/{id}\x12Z\n" +
	"\vDeleteTrack\x12\x19.track.DeleteTrackRequest\x1a\x1a.track.DeleteTrackResponse\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/tracks/{id}B\bZ\x06/trackb\x06proto3"

var (
	file_track_proto_rawDescOnce sync.Once
	file_track_proto_rawDescData []byte
)

func file_track_proto_rawDescGZIP() []byte {
	file_track_proto_rawDescOnce.Do(func() {
		file_track_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_track_proto_rawDesc), len(file_track_proto_rawDesc)))
	})
	return file_track_proto_rawDescData
}

var file_track_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_track_proto_goTypes = []any{
	(*Track)(nil),               // 0: track.Track
	(*CreateTrackRequest)(nil),  // 1: track.CreateTrackRequest
	(*CreateTrackResponse)(nil), // 2: track.CreateTrackResponse
	(*GetTrackRequest)(nil),     // 3: track.GetTrackRequest
	(*GetTrackResponse)(nil),    // 4: track.GetTrackResponse
	(*UpdateTrackRequest)(nil),  // 5: track.UpdateTrackRequest
	(*UpdateTrackResponse)(nil), // 6: track.UpdateTrackResponse
	(*DeleteTrackRequest)(nil),  // 7: track.DeleteTrackRequest
	(*DeleteTrackResponse)(nil), // 8: track.DeleteTrackResponse
}
var file_track_proto_depIdxs = []int32{
	0, // 0: track.CreateTrackRequest.track:type_name -> track.Track
	0, // 1: track.GetTrackResponse.track:type_name -> track.Track
	0, // 2: track.UpdateTrackRequest.track:type_name -> track.Track
	1, // 3: track.UserService.CreateTrack:input_type -> track.CreateTrackRequest
	3, // 4: track.UserService.GetTrack:input_type -> track.GetTrackRequest
	5, // 5: track.UserService.UpdateTrack:input_type -> track.UpdateTrackRequest
	7, // 6: track.UserService.DeleteTrack:input_type -> track.DeleteTrackRequest
	2, // 7: track.UserService.CreateTrack:output_type -> track.CreateTrackResponse
	4, // 8: track.UserService.GetTrack:output_type -> track.GetTrackResponse
	6, // 9: track.UserService.UpdateTrack:output_type -> track.UpdateTrackResponse
	8, // 10: track.UserService.DeleteTrack:output_type -> track.DeleteTrackResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_track_proto_init() }
func file_track_proto_init() {
	if File_track_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_track_proto_rawDesc), len(file_track_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_track_proto_goTypes,
		DependencyIndexes: file_track_proto_depIdxs,
		MessageInfos:      file_track_proto_msgTypes,
	}.Build()
	File_track_proto = out.File
	file_track_proto_goTypes = nil
	file_track_proto_depIdxs = nil
}
