env: "local"
grpc_port: 50054
internal_grpc_port: 50055
http_port: 8080
db_host: "localhost"
db_port: 5432
db_user: "postgres"
db_password: "postgres"
db_name: "user_service"
redis_host: "localhost"
redis_port: 6379
jwt_secret: "123"
access_expiration: 0
refresh_expiration: 0
token_issuer: 0
