env: "local"
grpc_port: 50051
http_port: 8080
db_host: ""
db_port: ""
db_user: ""
db_password: ""
db_name: ""
redis_host: ""
redis_port: ""
jwt_secret: ""
access_expiration: ""
refresh_expiration: ""
token_issuer: ""
